import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import { FiArrowRight } from "react-icons/fi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Infodiv>
          <div>
            <h1>This is Firmlytical</h1>
            <p>
              We provide a wide array of case files from our database. Browse
              through our extensive library from the courtroom to your corner
              office. ⭐️⭐️⭐️⭐️ Come take a peek....
            </p>
          </div>
        </Infodiv>
        <Imagediv>
          <Image
            src="/scale.jpg"
            alt="court"
            width={900}
            height={700}
            objectFit={"cover"}
          />
        </Imagediv>
      </Hero>
      <DataSection>
        <h1>Dive In</h1>
        <p>
          Start Exploring our data. Here are some categories you can use to
          check it out
        </p>
        <Datadiv>
          <div>
            <Image
              src="/search-files.svg"
              alt="search"
              width="150"
              height="150"
            />
            <h3>
              Search cases with an intuitive, powerful search engine interface.
            </h3>
            <button>
              <p>Search</p>
              <FiArrowRight />
            </button>
          </div>
          <div>
            <Image
              src="/see-trends.svg"
              alt="search"
              width="150"
              height="150"
            />
            <h3>
              Historical Trends lets you visualize the use of terms over time in
              caselaw.
            </h3>
            <button>
              <p>Trends</p>
              <FiArrowRight />
            </button>
          </div>
          <div>
            <Image src="/download.svg" alt="search" width="150" height="150" />
            <h3>
              Download the data in a variety of formats, including JSON, CSV,
              and XML.
            </h3>
            <button>
              <p>Download Files</p>
              <FiArrowRight />
            </button>
          </div>
        </Datadiv>
      </DataSection>
    </div>
  );
}

const Hero = styled.div`
  display: flex;
  width: 100%;
  @media (max-width: 768px) {
    flex-wrap: wrap;
  }
`;

const Infodiv = styled.div`
  background: #f8f0eb;
  flex-basis: 50%;
  padding: 16px;
  display: flex;
  align-items: center;
  width: 100%;
  div {
    margin: auto;
    h1 {
      font-size: 2.5rem;
      line-height: 1;
      padding: 5px;
      text-align: center;
      font-family: "Roboto", sans-serif;
    }
    p {
      font-size: 1.5rem;
      line-height: 1.5;
      font-weight: 400;
      padding: 5px;
      text-align: center;
    }
  }
  @media (max-width: 768px) {
    order: 2;
    flex-basis: 100%;
  }
`;

const Imagediv = styled.div`
  flex-basis: 50%;
  @media (max-width: 768px) {
    order: 1;
    flex-basis: 100%;
  }
`;

const DataSection = styled.div`
  background: #d8f4ed;
  padding: 1rem;
  h1 {
    font-size: 2rem;
    font-weight: 500;
    text-align: center;
    padding: 5px;
    margin-top: 1rem;
    font-family: "Roboto", sans-serif;
  }
  p {
    font-size: 1.2rem;
    font-weight: 400;
    text-align: center;
    padding: 5px;
  }
`;

const Datadiv = styled.div`
  display: flex;
  justify-content: space-between;
  margin-top: 1rem;
  div {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 15px;
    gap: 1rem;
    h3 {
      font-size: 1rem;
      padding: 5px;
      text-align: center;
    }
    button {
      padding: 0.5rem 1rem;
      border: 1px solid #000;
      color: black;
      background: white;
      display: flex;
      align-items: center;
      gap: 0.5rem;
      cursor: pointer;
      p {
        font-size: 1rem;
      }
      svg {
        font-size: 1rem;
      }
      &:hover {
        background: black;
        color: white;
        svg {
          transform: translateX(5px);
          transform: scaleX(1.4);
          transition: 0.2s ease-in;
        }
      }
    }
  }
  @media (max-width: 768px) {
    flex-direction: column;
    gap: 1rem;
  }
`;
